### ISSUE TITLE
Availability 

### ISSUE THREAD

**Issue by eddiejaoude** [empowerhack/Family-MemberService#5]
A way to understand Members availability.

> Han and i are talking and we wondefing if you can create a slider for when people are available/not available for month/week the  we know when they are availablr not just days/times.

**Comment by herahussain** [comment]
So what we're trying to say is, someone might be part of the Family but not be available during February but is totally in for April. This should allow them to say what Months they are available and also the extend to which they are available. Like a slider:
I HAVE A LOT OF TIME -----------------------------------------------------------> I HAVE NO TIME

**Comment by eddiejaoude** [comment]
Oh I see, ok.

Do you think monthly is too broad for some? then weekly is too granular for others? What about availability on their current status?

**Comment by eddiejaoude** [comment]
I will do it as a percentage for now
